import pandas as pd
from datetime import datetime, date

data = [
    {
        "customer_id": "CUST-1001",
        "customer_name": "Aarav Sharma",
        "mobile": "9876543210",
        "email": "aarav.sharma@example.com",
        "service_type": "SaaS Subscription",
        "plan_or_loan_name": "TechFlow Enterprise Cloud Monthly",
        "due_amount": 2499.00,
        "currency": "INR",
        "due_date": "2026-09-28",
        "failed_date": "2026-09-29",
        "payment_method": "HDFC Debit Card e-Mandate",
        "failure_reason": "Insufficient Balance",
        "payment_link": "https://rzp.io/i/rec_1001_aarav",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1002",
        "customer_name": "Priya Patel",
        "mobile": "9812345678",
        "email": "priya.patel@example.com",
        "service_type": "OTT Subscription",
        "plan_or_loan_name": "StreamFlix 4K Annual Plan",
        "due_amount": 1499.00,
        "currency": "INR",
        "due_date": "2026-09-30",
        "failed_date": "2026-10-01",
        "payment_method": "ICICI Credit Card Autopay",
        "failure_reason": "Expired Card",
        "payment_link": "https://rzp.io/i/rec_1002_priya",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1003",
        "customer_name": "Rahul Verma",
        "mobile": "9988776655",
        "email": "rahul.verma@example.com",
        "service_type": "Personal Loan EMI",
        "plan_or_loan_name": "FinEasy Personal Loan EMI #7",
        "due_amount": 8750.00,
        "currency": "INR",
        "due_date": "2026-10-01",
        "failed_date": "2026-10-01",
        "payment_method": "SBI eNACH Mandate",
        "failure_reason": "Insufficient Funds in Account",
        "payment_link": "https://rzp.io/i/rec_1003_rahul",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1004",
        "customer_name": "Sneha Mukherjee",
        "mobile": "9711223344",
        "email": "sneha.m@example.com",
        "service_type": "Broadband / Utility",
        "plan_or_loan_name": "AeroFiber 500Mbps Broadband",
        "due_amount": 1179.00,
        "currency": "INR",
        "due_date": "2026-09-25",
        "failed_date": "2026-09-26",
        "payment_method": "UPI Autopay (GPay / Axis)",
        "failure_reason": "UPI Mandate Limit Exceeded",
        "payment_link": "https://rzp.io/i/rec_1004_sneha",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1005",
        "customer_name": "Vikramaditya Rao",
        "mobile": "9823456789",
        "email": "vikram.rao@example.com",
        "service_type": "Health Insurance Premium",
        "plan_or_loan_name": "CareShield Health Annual Premium",
        "due_amount": 14200.00,
        "currency": "INR",
        "due_date": "2026-09-29",
        "failed_date": "2026-09-30",
        "payment_method": "Kotak Netbanking eNACH",
        "failure_reason": "Bank Server Timeout / Technical Failure",
        "payment_link": "https://rzp.io/i/rec_1005_vikram",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1006",
        "customer_name": "Ananya Iyer",
        "mobile": "9845012345",
        "email": "ananya.iyer@example.com",
        "service_type": "Fitness Membership",
        "plan_or_loan_name": "FitPulse Gym & Yoga Monthly",
        "due_amount": 3200.00,
        "currency": "INR",
        "due_date": "2026-10-01",
        "failed_date": "2026-10-02",
        "payment_method": "Paytm UPI Autopay",
        "failure_reason": "Bank Account Dormant / Inactive",
        "payment_link": "https://rzp.io/i/rec_1006_ananya",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1007",
        "customer_name": "Rohan Gupta",
        "mobile": "9830112233",
        "email": "rohan.gupta@example.com",
        "service_type": "EdTech / Course EMI",
        "plan_or_loan_name": "SkillUp Data Science Bootcamp EMI #3",
        "due_amount": 5500.00,
        "currency": "INR",
        "due_date": "2026-09-27",
        "failed_date": "2026-09-28",
        "payment_method": "Axis Bank Debit Card",
        "failure_reason": "Insufficient Balance",
        "payment_link": "https://rzp.io/i/rec_1007_rohan",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1008",
        "customer_name": "Neha Singh",
        "mobile": "9890998877",
        "email": "neha.singh@example.com",
        "service_type": "Credit Card Minimum Due",
        "plan_or_loan_name": "Prime Bank Titanium Card Autopay",
        "due_amount": 4850.00,
        "currency": "INR",
        "due_date": "2026-09-29",
        "failed_date": "2026-09-30",
        "payment_method": "HDFC Savings Account e-Mandate",
        "failure_reason": "Customer Requested Stop Payment",
        "payment_link": "https://rzp.io/i/rec_1008_neha",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1009",
        "customer_name": "Kavita Reddy",
        "mobile": "9848011223",
        "email": "kavita.reddy@example.com",
        "service_type": "Cloud Storage / Software",
        "plan_or_loan_name": "CloudVault 2TB Pro Plan",
        "due_amount": 799.00,
        "currency": "INR",
        "due_date": "2026-09-30",
        "failed_date": "2026-10-01",
        "payment_method": "ICICI Debit Card",
        "failure_reason": "Card Blocked / Reissued",
        "payment_link": "https://rzp.io/i/rec_1009_kavita",
        "payment_status": "UNPAID"
    },
    {
        "customer_id": "CUST-1010",
        "customer_name": "Amitabh Joshi",
        "mobile": "9820054321",
        "email": "amitabh.joshi@example.com",
        "service_type": "Vehicle Loan EMI",
        "plan_or_loan_name": "SpeedFinance Two-Wheeler Loan EMI #12",
        "due_amount": 3650.00,
        "currency": "INR",
        "due_date": "2026-10-01",
        "failed_date": "2026-10-02",
        "payment_method": "PNB eNACH Mandate",
        "failure_reason": "Insufficient Balance",
        "payment_link": "https://rzp.io/i/rec_1010_amitabh",
        "payment_status": "UNPAID"
    }
]

df = pd.DataFrame(data)
df.to_excel("dummy_autopay_records.xlsx", index=False)
df.to_csv("dummy_autopay_records.csv", index=False)
print("Successfully created dummy_autopay_records.xlsx and dummy_autopay_records.csv with 10 fictional records.")
